import jsPDF from 'jspdf';

/**
 * Helper to convert an SVG Data URI to a high-res PNG Data URI using a canvas.
 * This ensures compatibility with jsPDF which struggles with direct SVGs.
 */
const svgToPng = (svgDataUrl: string, width: number = 2000, height: number = 2000): Promise<string> => {
    return new Promise((resolve, reject) => {
        const img = new Image();
        img.crossOrigin = 'Anonymous';
        img.onload = () => {
            const canvas = document.createElement('canvas');
            canvas.width = width;
            canvas.height = height;
            const ctx = canvas.getContext('2d');
            if (!ctx) {
                reject(new Error('Could not get canvas context'));
                return;
            }
            // Fill white background (SVGs might be transparent)
            ctx.fillStyle = '#FFFFFF';
            ctx.fillRect(0, 0, width, height);
            ctx.drawImage(img, 0, 0, width, height);
            resolve(canvas.toDataURL('image/png'));
        };
        img.onerror = (e) => reject(e);
        img.src = svgDataUrl;
    });
};

/**
 * Generates a single page PDF with the coloring image.
 */
export const generateSinglePagePDF = async (imageUrl: string, prompt: string) => {
    // Create A4 PDF (210mm x 297mm)
    const doc = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4',
    });

    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 20;
    const imageSize = pageWidth - (margin * 2);

    // Add Title
    doc.setFontSize(16);
    doc.text("AI Coloring Page", pageWidth / 2, margin, { align: 'center' });

    // Add Prompt as Subtitle
    doc.setFontSize(12);
    doc.setTextColor(100);
    const splitPrompt = doc.splitTextToSize(prompt, imageSize);
    doc.text(splitPrompt, pageWidth / 2, margin + 10, { align: 'center' });

    // Add Image
    try {
        // Convert SVG to PNG first
        const pngUrl = await svgToPng(imageUrl);
        doc.addImage(pngUrl, 'PNG', margin, margin + 20, imageSize, imageSize);
    } catch (e) {
        console.error("Error adding image to PDF", e);
        doc.text("Error loading image", pageWidth / 2, pageHeight / 2, { align: 'center' });
    }

    // Add Footer
    doc.setFontSize(10);
    doc.setTextColor(150);
    doc.text("Generated by ai-coloringpage.com", pageWidth / 2, pageHeight - 10, { align: 'center' });

    // Save
    doc.save(`coloring-page-${Date.now()}.pdf`);
};

/**
 * Generates a multi-page PDF "Coloring Book".
 */
export const generateBookPDF = async (images: Array<{ url: string; prompt: string }>) => {
    const doc = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4',
    });

    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 20;
    const imageSize = pageWidth - (margin * 2);

    // Cover Page
    doc.setFontSize(30);
    doc.text("My Coloring Book", pageWidth / 2, pageHeight / 3, { align: 'center' });

    doc.setFontSize(14);
    doc.text(`Contains ${images.length} unique pages`, pageWidth / 2, (pageHeight / 3) + 20, { align: 'center' });

    doc.setFontSize(10);
    doc.setTextColor(150);
    doc.text(`Generated on ${new Date().toLocaleDateString()}`, pageWidth / 2, pageHeight - 20, { align: 'center' });

    // Add Pages
    for (let i = 0; i < images.length; i++) {
        const item = images[i];
        doc.addPage();

        // Page Number
        doc.setFontSize(10);
        doc.setTextColor(150);
        doc.text(`Page ${i + 1}`, pageWidth - margin, margin, { align: 'right' });

        // Prompt
        doc.setFontSize(12);
        doc.setTextColor(0);
        const splitPrompt = doc.splitTextToSize(item.prompt, imageSize);
        doc.text(splitPrompt, pageWidth / 2, margin + 10, { align: 'center' });

        // Image
        try {
            const pngUrl = await svgToPng(item.url);
            doc.addImage(pngUrl, 'PNG', margin, margin + 20, imageSize, imageSize);
        } catch (e) {
            console.error(`Error adding image ${i} to PDF`, e);
        }

        // Footer
        doc.setFontSize(10);
        doc.setTextColor(150);
        doc.text("ai-coloringpage.com", pageWidth / 2, pageHeight - 10, { align: 'center' });
    }

    doc.save(`my-coloring-book-${Date.now()}.pdf`);
};
