
import fs from 'fs';
import path from 'path';
import dotenv from 'dotenv';
import { createClient } from '@supabase/supabase-js';
import sharp from 'sharp';

// Load environment variables
dotenv.config({ path: '.env.local' });

const PINTEREST_ACCESS_TOKEN = process.env.PINTEREST_ACCESS_TOKEN;
const PINTEREST_BOARD_ID = process.env.PINTEREST_BOARD_ID;
const GOOGLE_API_KEY = process.env.GOOGLE_GENERATIVE_AI_API_KEY;
const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL;
const SUPABASE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

if (!PINTEREST_ACCESS_TOKEN || !PINTEREST_BOARD_ID || !GOOGLE_API_KEY || !SUPABASE_URL || !SUPABASE_KEY) {
    console.error('Missing required environment variables. Please check .env.local');
    process.exit(1);
}

const supabase = createClient(SUPABASE_URL, SUPABASE_KEY);
const DATA_FILE = path.join(process.cwd(), 'src', 'data', 'seo-pages.json');

// Gemini Generation Function (Mirrors src/app/actions/gen-img.ts)
async function generateImage(prompt: string) {
    // Use the EXACT model name from the working web app
    const model = 'gemini-2.5-flash-image';
    const url = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${GOOGLE_API_KEY}`;

    // Use the EXACT prompt structure from the working web app
    const fullPrompt = `Generate a black and white coloring page of ${prompt}. Do not include any text in the image.`;

    const response = await fetch(url, {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
        },
        body: JSON.stringify({
            contents: [{
                parts: [{ text: fullPrompt }]
            }],
            generationConfig: {
                temperature: 0.7,
            }
        })
    });

    if (!response.ok) {
        const errorText = await response.text();
        throw new Error(`Gemini API Error: ${response.status} ${response.statusText} - ${errorText}`);
    }

    const data = await response.json();

    // DEBUG: Log if no candidates
    if (!data.candidates || data.candidates.length === 0) {
        console.log('DEBUG: No candidates in response:', JSON.stringify(data, null, 2));
    }

    const candidate = data.candidates?.[0];
    const parts = candidate?.content?.parts || [];
    const imagePart = parts.find((part: any) => part.inlineData);

    if (!imagePart) {
        // Check if it returned text instead
        const textPart = parts.find((part: any) => part.text);
        if (textPart) {
            console.log(`DEBUG: Model returned text: "${textPart.text}"`);
        }
        throw new Error('No image generated by Gemini (returned text or empty)');
    }

    return imagePart.inlineData.data; // Base64 string
}

// Pinterest Post Function
async function postToPinterest(imageUrl: string, title: string, description: string, link: string) {
    const url = `https://api.pinterest.com/v5/pins`;
    console.log(`  - Posting to Pinterest...`);
    const body = {
        board_id: PINTEREST_BOARD_ID,
        title: title,
        description: description,
        link: link,
        media_source: {
            source_type: 'image_url',
            url: imageUrl
        }
    };

    const response = await fetch(url, {
        method: 'POST',
        headers: {
            'Authorization': `Bearer ${PINTEREST_ACCESS_TOKEN}`,
            'Content-Type': 'application/json'
        },
        body: JSON.stringify(body)
    });

    if (!response.ok) {
        const err = await response.text();
        throw new Error(`Pinterest API Error: ${err}`);
    }

    return await response.json();
}

async function main() {
    console.log('Starting Pinterest Auto-Poster (Web App Logic)...');

    const fileContent = fs.readFileSync(DATA_FILE, 'utf8');
    const pages = JSON.parse(fileContent);

    let postedCount = 0;

    // Random Daily Limit (20-40)
    const minPins = 20;
    const maxPins = 40;
    const dailyLimit = Math.floor(Math.random() * (maxPins - minPins + 1)) + minPins;
    console.log(`\n🎯 Daily Safety Target: ${dailyLimit} Pins (Randomized 20-40)`);

    for (let i = 0; i < pages.length; i++) {
        const page = pages[i];

        if (page.pinterest_posted) {
            continue;
        }

        // Safety Cap check at start of loop
        if (postedCount >= dailyLimit) {
            console.log(`\n🛑 DAILY SAFETY LIMIT REACHED (${dailyLimit} Pins)`);
            console.log('   Stopping to protect your Pinterest account health.');
            console.log('   Run this script again tomorrow!');
            break;
        }

        console.log(`Processing [${i + 1}/${pages.length}]: ${page.title}`);

        try {
            // 1. Generate Image
            console.log('  - Generating image...');
            const base64Image = await generateImage(page.prompt);
            const buffer = Buffer.from(base64Image, 'base64');

            // Optimize with Sharp (Best for Line Art)
            // Format: WebP (Lossless-ish) - No JPEG artifacts, tiny file size
            // Size: 1024x1024 (Native AI)
            const optimizedBuffer = await sharp(buffer)
                .resize(1024, 1024, { fit: 'inside' })
                .webp({ quality: 80, effort: 6 }) // Effort 6 = Max compression
                .toBuffer();

            // 2. Upload to Supabase
            console.log('  - Uploading to Supabase...');
            const fileName = `${page.slug}-${Date.now()}.webp`; // Changed to .webp
            const { data: uploadData, error: uploadError } = await supabase
                .storage
                .from('seo-images')
                .upload(fileName, optimizedBuffer, {
                    contentType: 'image/webp',
                    upsert: true
                });

            if (uploadError) throw new Error(`Upload failed: ${uploadError.message}`);

            const { data: { publicUrl } } = supabase
                .storage
                .from('seo-images')
                .getPublicUrl(fileName);

            // 3. Post to Pinterest
            console.log('  - Posting to Pinterest...');
            const link = `${process.env.NEXT_PUBLIC_BASE_URL || 'https://ai-coloringpage.com'}/printable/${page.slug}`;
            await postToPinterest(publicUrl, page.title, page.description, link);

            // 4. Update Supabase Database (Real-time sync for website)
            console.log('  - Updating Supabase DB...');
            const { error: dbError } = await supabase
                .from('seo_pages')
                .upsert({
                    slug: page.slug,
                    title: page.title,
                    description: page.description,
                    prompt: page.prompt,
                    image_url: publicUrl,
                    pinterest_posted: true,
                    updated_at: new Date().toISOString()
                }, { onConflict: 'slug' });

            if (dbError) {
                console.error(`  - DB Update Failed: ${dbError.message}`);
                // Don't stop the script, just log it. The local JSON is still a backup.
            }

            // 5. Update Local Data
            page.image_url = publicUrl;
            page.pinterest_posted = true;
            fs.writeFileSync(DATA_FILE, JSON.stringify(pages, null, 2));

            console.log('  - Success! ✅');
            postedCount++;

            // Rate Limit Delay (45s + Random 0-30s Jitter)
            // This makes the posting pattern look more human and less robotic.
            const jitter = Math.floor(Math.random() * 30000);
            const delay = 45000 + jitter;

            console.log(`  - Waiting ${Math.round(delay / 1000)}s (Safety Jitter)...`);
            await new Promise(resolve => setTimeout(resolve, delay));

        } catch (error: any) {
            const errorMessage = error.toString();
            console.error(`  - Failed: ${errorMessage}`);

            // Check for Pinterest Spam Block (Code 9)
            if (errorMessage.includes('"code":9') || errorMessage.includes('spam')) {
                console.log('\n⚠️  PINTEREST SPAM BLOCK DETECTED! ⚠️');
                console.log('   The script is posting too fast. Cooling down for 10 minutes...');
                console.log('   (Go grab a coffee ☕️)\n');

                // Wait 10 minutes
                await new Promise(resolve => setTimeout(resolve, 10 * 60 * 1000));
                console.log('   Resuming...\n');
            } else {
                console.log('  - Waiting 20s after error...');
                await new Promise(resolve => setTimeout(resolve, 20000));
            }
        }
    }

    console.log(`Finished! Posted ${postedCount} new pins.`);
}

main();
